name: reusable workflow
on: workflow_call
jobs:
    Print_dummy_message:
     runs-on: ubuntu-latest
     steps:
      - name: add dummy data to artifact
        run: |
         echo "I'm dummy data in an artifact" >> artifact.txt

      - name: upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: dummy-artifact
          path: artifact.txt
