name: run data extractor

on:
  workflow_dispatch:


jobs:
  trigger-trace-analyzer-workflow:
    runs-on: windows_latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Run data extractor 
        run: |
          cd /Python_Scripts
          python Extract_Data_From_Json.py --../Json_files/Test_Sets.json
         
