name: run data extractor

on:
  workflow_dispatch:


jobs:
  trigger-trace-analyzer-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Run data extractor 
        run: |
          python Python_Scripts/Extract_Data_From_Json.py --Json_files/Test_Sets.json
         
