name: run data extractor

on:
  workflow_dispatch:
  push:


jobs:
  trigger-trace-analyzer-workflow:
    outputs:
      CN_IDs: ${{ steps.Run_data_extractor.outputs }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Run data extractor
        id: Run_data_extractor
        run: |
          python Python_Scripts/Extract_Data_From_Json.py Json_files/Test_Sets.json
      - name: use output
        id: use_output
        run: |
          echo ${{ steps.Run_data_extractor.CN_IDs }}
          
         
