name: run data extractor

on:
  workflow_dispatch:
   inputs:
    test_set_path:
        description: 'The path to a test set file'
        required: false
        type: string


jobs:
  trigger-data-extractor-workflow:
    continue-on-error: true
    strategy: 
      matrix:
        operating-systems: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.operating-systems}}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
                  
      - name: Run data extractor
        id: Run_data_extractor
        run: |
          python Python_Scripts/Extract_Data_From_Json.py --test_set_path=${{ inputs.test_set_path }}
          
      - name: Read output from script
        run: |
          echo "campaign_name:${{ steps.Run_data_extractor.outputs.campaign_name }}"
          echo "id_list:${{ steps.Run_data_extractor.outputs.id_list }}"
          echo "test_set_id:${{ steps.Run_data_extractor.outputs.test_set_id }}"

           
          
         
