name: run data extractor

on:
  workflow_dispatch:
  push:


jobs:
  trigger-trace-analyzer-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Write output
        id: write_output
        run: |          
          echo "campaign_name=key1" >> "$GITHUB_OUTPUT"
          echo "id_list=key2" >> "$GITHUB_OUTPUT"
          echo "test_set_id=key3" >> "$GITHUB_OUTPUT"
          
      - name: Run data extractor
        id: Run_data_extractor
        run: |
          python Python_Scripts/Extract_Data_From_Json.py Json_files/Test_Sets.json
          
      - name: Read output from script
        run: |
          echo "campaign_name: ${{ steps.Run_data_extractor.outputs.campaign_name }}"
          echo "id_list:${{ steps.Run_data_extractor.outputs.id_list }}"
          echo "test_set_id:  ${{ steps.Run_data_extractor.outputs.test_set_id }}"

           
          
         
