name: run data extractor

on:
  workflow_dispatch:


jobs:
  trigger-trace-analyzer-workflow:
    runs-on: windows_latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Run data extractor
        env:
            JSON_FILE_PATH: ${{MedhatMasry/TrialRepo/Json_files/Test_Sets.json}}
        run: |
          cd /Python_Scripts
          python Extract_Data_From_Json.py --${{ JSON_FILE_PATH }}
         
