name: run data extractor

on:
  workflow_dispatch:
    inputs:
      json_file_path:
        description: 'The path to a json file'
        required: false
        type: string


jobs:
  trigger-trace-analyzer-workflow:
    runs-on: windows_latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3